#!/usr/bin/env node

const exec = require('child_process').execSync;

const WORKDIR = '/usr/src/app/note';
process.chdir(WORKDIR);

// git pull 
exec('git pull origin master');

// npm i 
exec('npm i');

// build 
exec('npx hexo g');

// start server
exec('npx  http-server -s -p 8080 ./public')

